id: IAFF72048
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:20:12.166988
last_modified: 2023-02-08 15:20:12.167113
source_metadata:
  title: 'PP: Ratnaguṇasaṃcayagāthā'
  language: zh
bases:
  C786:
    base_file: C786.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
